import Navbar from "@/components/Navbar.react";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
import { Capriola } from "next/font/google";

// Header font
const capriola = Capriola({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex w-full flex-col p-8">
          <div className="self-center">
            <h1
              className={["text-center text-4xl", capriola.className].join(" ")}
            >
              Scott O&apos;Brien
            </h1>
            <Navbar />
          </div>
          <div className="max-w-2xl w-[80%] self-center mt-2">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
